name: 'docker-swarm-deploy-github-action'
description: 'Deploy your Docker Swarm apps in seconds. 🚀'
inputs:
  deployment_ssh_private_key:
    description: 'The private key you have authenticated to connect to your server via SSH.'
    required: true
  remote_ssh_known_hosts:
    description: 'The public key of your SSH server to validate we are connecting to the right server.'
    required: true
  remote_ssh_deployment_user:
    description: 'The user that you would like to connect as on the remote server via SSH.'
    required: true
  remote_ssh_server:
    description: 'The hostname or IP address of the server you want to connect to.'
    required: true
  remote_ssh_port:
    description: 'The SSH port of the remote server you would like to connect to.'
    default: '22'
    required: false
  docker_compose_file_path:
    description: 'Set your docker compose file path with the CLI options.'
    default: '-c docker-compose.yml -c docker-compose.prod.yml'
    required: false
  ssh_key_id:
    description: 'Set your key type/id (id_ed25519, id_rsa, etc)'
    default: 'id_ed25519'
runs:
  using: 'composite'
  steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        name: ${{ inputs.ssh_key_id }}
        key: ${{ inputs.deployment_ssh_private_key }}
        known_hosts: ${{ inputs.remote_ssh_known_hosts }}

    - name: Set the current time to the "NOW" variable
      run: NOW=$(date +%s)
      shell: bash
    
    - name: Debug SSH command
      run: |
        ssh -vvvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ inputs.remote_ssh_port }} ${{ inputs.remote_ssh_deployment_user }}@${{ inputs.remote_ssh_server }} cat /etc/hostname
      shell: bash

    - name: Run the Docker Swarm deployment
      run: |
        docker --log-level debug -H ssh://${{ inputs.remote_ssh_deployment_user }}@${{ inputs.remote_ssh_server }}:${{ inputs.remote_ssh_port }} \
          stack deploy --with-registry-auth \
          ${{ inputs.docker_compose_file_path }} \
          ${GITHUB_REPOSITORY#*/} --prune
      shell: bash

branding:
  icon: 'zap'
  color: 'blue'
